### PR TITLE
upload-1187 translate post finish to go

### PR DESCRIPTION
**Pull request by USZ7**
Translate 'post finish' to go

### CODE REVIEW

**Review by whytheplatypus — CHANGES_REQUESTED** [review]
Great start please move this into the go code, similar to the one triggered here: https://github.com/CDCgov/data-exchange-upload/blob/main/upload-server/cmd/cli/hooks.go#L93

**Comment by whytheplatypus** [comment]
This looks like most of the behavior was around traces, so do we still need this hook or can it be deprecated entirely?

**Comment by USZ7** [comment]
> Great start please move this into the go code, similar to the one triggered here: https://github.com/CDCgov/data-exchange-upload/blob/main/upload-server/cmd/cli/hooks.go#L93

Done!

**Comment by USZ7** [comment]
> This looks like most of the behavior was around traces, so do we still need this hook or can it be deprecated entirely?

@cosmycx  @cfarmer-fearless let's get your thoughts on this before we implement the code change.

**Review by cfarmer-fearless — CHANGES_REQUESTED** [review]
This hook's only responsibility is to stop a span in PS API, which is deprecated.  Therefore, this hook can be removed entirely and does not need to be translated to GoLang.

**Comment by USZ7** [comment]
> This hook's only responsibility is to stop a span in PS API, which is deprecated. Therefore, this hook can be removed entirely and does not need to be translated to GoLang. This PR can be closed, and corresponding Jira ticket canceled.

@cfarmer-fearless Gotcha, thanks! I'll close it out. CC @whytheplatypus

**Comment by USZ7** [comment]
The 'post finish' hook can be removed entirely and does not need to be translated to GoLang. Based on the feedback, this PR can be closed.

**Pull request closed without merging**
